### ISSUE TITLE
This is RedLine stealer

### ISSUE THREAD

**Issue by CF-Clezy** [HertZxD/GrowPai#25]
![redline](https://github.com/HertZxD/GrowPai/assets/147587438/4aa46326-5679-455c-934b-2b2accf8f137)

**Comment by HertZxD** [comment]
me when looking at that file size 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭
